### ISSUE TITLE
Question: why is there no update action?

### ISSUE THREAD

**Issue by justme234** [rla/sql-sync#1]
I love your code here.  Great work!

My only question (and probably a dumb one):

Why do you mark a DELETE then an ADD for every update on a table?

CREATE TRIGGER <table>_update
AFTER UPDATE ON <table> FOR EACH ROW
BEGIN
    INSERT INTO sync(action, keyval, tid)
    VALUES (1, OLD.<keycol>, <tableid>);
    INSERT INTO sync(action, keyval, tid)
    VALUES (0, NEW.<keycol>, <tableid>);
END;

I'm sure there's a logical reason, but I can't for the life of me think what it is.

Thanks for your reply

**Comment by rla** [comment]
Hello,

I think the reason was a simpler logical model as you do not have to deal with separate `update` actions, only `add` and `delete` actions are necessary.

I think the further question is why it cannot simply be `add` for the update case. Or can it be?

I think the corner case here would be the case where the key itself is updated. In that case there will be 2 entries in the client `sync` table, to delete the row with the previous key value and to add row with the new key value.

If the key value does not change, the `add` action in the sync table overwrites the `delete` action and the `delete` action is never used.

**Comment by rla** [comment]
If you think that key changes would never happen then you could possibly drop the `delete` action statement from the update trigger. Key change could be guarded against with `RAISE()` to throw an error from the trigger. This should work well if you have operations wrapped inside transactions.

**Comment by justme234** [comment]
Awesome, thanks!  I wasn't thinking of the possibility of the key changing, but I can see how a 'delete' and then an 'update' action makes sense in that case.

Thanks so much for your quick reply.
